Zaid/sustain 27
skaarkzo-capstone/client-frontend pull request #16
Opened 2024-12-26 22:01 UTC by zaidokal

# JIRA Ticket Link

https://skaarkzo-capstone.atlassian.net/browse/SUSTAIN-27

# Summary of Changes

Adding colored scores to Card and overlay
Separated DTOs
Refactoring code

2024-12-26 23:30 UTC, rakhshankhan requested changes

2024-12-26 23:30 UTC, rakhshankhan commented on src/app/hooks/utils/CompanyDTO.ts
DTO is specifically used in the backends as a way to denote your response schemas. Since the ones in the frontend have slightly different data models, these would be considered interfaces. Lets make this file just be "company.ts" under a folder called "interface" rather than utils.

2024-12-26 23:30 UTC, rakhshankhan commented on src/app/hooks/utils/CompanyDTO.ts
> +type Company = {
As mentioned with the naming conventions:
```suggestion
interface Company = {
```

2024-12-27 00:36 UTC, zaidokal commented on src/app/hooks/utils/CompanyDTO.ts
> +type Company = {
In that case, it should be interface Company { (whithout the = sign).
Committed the changes

2024-12-27 00:36 UTC, zaidokal commented on src/app/hooks/utils/CompanyDTO.ts
Done

2024-12-27 00:46 UTC, rakhshankhan approved these changes

2024-12-28 04:37 UTC, skhan943 approved these changes
LGTM

2024-12-28 04:47 UTC, merged